### ISSUE TITLE
error when installing in windows 10

### ISSUE THREAD

**Issue by evilzkun** [pik-copan/pyunicorn#127]
Trying to install in a Windows 10 system. It has anaconda and visual c++ build tools 14 installed. I get the cl.exe unable to start error.
Thus unable to build wheel. Please upload the wheel file on pypi or here.

**Comment by zhouqiaor** [comment]
Please upload the wheel file on pypi or here, i have the same problem.

**Comment by fred-fp** [comment]
Is there a way to install it without the wheel file? Because its not working at all with pip

**Comment by Liyubov** [comment]
**Hi! 
I also had the same problem. Here is the error message:** 

 If the compilation fails and you are sure that igraph is installed
  on your machine, adjust the following two variables in setup.py
  accordingly and try again:

  - LIBIGRAPH_FALLBACK_INCLUDE_DIRS
  - LIBIGRAPH_FALLBACK_LIBRARY_DIRS

  Continuing in 10 seconds; press Enter to continue immediately. error: [WinError 10038] An operation was attempted on something that is not a socket

  ----------------------------------------
  Failed building wheel for python-igraph
  Running setup.py clean for python-igraph
Failed to build pyunicorn python-igraph 

Thank you!

**Comment by jkroenke** [comment]
Apparently, python-igraph does not support automatic installation via pip on windows (see https://igraph.org/python/). Manual installation of python-igraph before using 'pip install pyunicorn' should solve the issue.

**Comment by dingfengqian** [comment]
@jkroenke 
I have tried to install python-igraph before the installationi of pyunicorn, but it still failed, the error it appeared are " error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2"      
it seemed that the error caused by vs. and both python of 3.6 and 3.7 on my windows have been tested, it resulted in the same errors.

**Comment by jkroenke** [comment]
@dingfengqian 
This might be a different problem. Can you provide more information on how you tried to install pyunicorn and when exactly the error appeared?

**Comment by dingfengqian** [comment]
the environment i am using is Windows 10 Python 3.6.2 and Python 3.7

and I have installed python-igraph before the installationi of pyunicorn&nbsp; 
then I directly enter "pip install pyunicorn" on cmd，and the error is showed below:
thanks for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jkroenke"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 晚上9:03
收件人:&nbsp;"pik-copan/pyunicorn"<pyunicorn@noreply.github.com&gt;;
抄送:&nbsp;"赚到一个亿后再改名"<1079874473@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pik-copan/pyunicorn] error when installing in windows 10 (#127)




@dingfengqian
 This might be a different problem. Can you provide more information on how you tried to install pyunicorn and when exactly the error appeared?

**Comment by XMAHA** [comment]
I have the same problem, have you guys sovled?

**Comment by nikfrlv** [comment]
> I have the same problem, have you guys sovled?

Yeah, I've solved this problem for Windows 10 x64 and notified the developers about it. Anyway, contact me if you need some help

**Comment by Nikos-T** [comment]
> 
> 
> > I have the same problem, have you guys sovled?
> 
> Yeah, I've solved this problem for Windows 10 x64 and notified the developers about it. Anyway, contact me if you need some help

Hello, how did you solve it?

**Comment by yop0** [comment]
Hello

> > I have the same problem, have you guys sovled?
> 
> Yeah, I've solved this problem for Windows 10 x64 and notified the developers about it. Anyway, contact me if you need some help

I have the same problem too, how did you solve it?

**Comment by nikfrlv** [comment]
@XMAHA @Nikos-T @yop0 hi, guys! After a few hours of coding I've compiled the .whl file for pyunicorn package. It works correct - tested for Windows 10 x64. Please, contact the developers of pyunicorn as I have the .whl file them.

**Comment by yop0** [comment]
Hi @nikfrlv ! 
The developers of pyunicorn kindly provided me with your wheel file. 
It worked "out-of-the-box" in a new Conda (v4.8.2) env.
Thanks a lot for your help!

**Comment by jdonges** [comment]
Hi @nikfrlv <https://github.com/nikfrlv> ,

if that would be OK for you, could you please post the link to your wheel file in this thread?

We’ll add a download link to the docs or somewhere else appropriate once more people have tested it (pyunicorn core developers at PIK are all
working on Linux and macOS, not Windows…)

Best,
Jonathan

**Comment by nikfrlv** [comment]
Hi Jonathan @jdonges,

I've uploaded the .whl file in this repository: https://github.com/nikfrlv/pyunicorn-windows-whl.
I encourage Windows-users to download it and use it in their research.

Best,
Nikita

**Comment by maldeer-Winlab** [comment]
Hi, @nikfrlv 

Did you get it to work on windows 10 ?
I use the conda terminal for installation and I am intending to use it with Jyupter...but I am getting errors!

Thanks

**Comment by nikfrlv** [comment]
Hi, @maldeer-Winlab 

yes, this has been done exactly for windows 10 x64. My colleagues use it as well.
Do you have errors during installation or during the compilation of the package Jupyter notebook?

**Comment by maldeer-Winlab** [comment]
Hi, @nikfrlv 
Thank you for your reply. 
Yes, I am getting errors during installation. I got it installed before but removed the package as it was not running. However, now I am not able to reinstall it (even without using the cached package)
Please see the attached

 snapshots 

Any advice is appreciated

[errors.pdf](https://github.com/pik-copan/pyunicorn/files/4557162/errors.pdf)

**Comment by nikfrlv** [comment]
@maldeer-Winlab

Please, try the following test:
(1) create an empty Python 3.7 conda environment;
(2) install numpy, scipy, matplotlib and cython packages using pip tool.
(3) install python-igraph package using pre-compiled .whl file (available here https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph)
(4) finally, install pyunicorn package using my .whl file.

If it's done correctly - it should work. At least, I've done this test right now.
If you still have some problems, check that you use Python 3.7 and Windows 10 x64.

Please, respond if you still have issues here.

**Comment by maldeer-Winlab** [comment]
@nikfrlv Thank you again for getting back to me
I did the test but I got an error. Please see the attached file with snapshots. Am I doing something wrong?
Should I uninstall everything....I mean the Anaconda and all IDEs and install Anaconda again?...but hopefully this does not affect my codes! 

Your help is appreciated as I need to use Pyunicorn to create recurrence plots for my research. 
Thank you

![error](https://user-images.githubusercontent.com/59928475/80730657-d5ee7e00-8ad7-11ea-9330-b82660fdacc9.jpg)

**Comment by nikfrlv** [comment]
@maldeer-Winlab

No, you don't have to uninstall anaconda. 

Please pay attention to the compatibility of the pre-compiled .whl file of the python-igraph package with your Python version. 
As I see in the attached snapshot, you've downloaded .whl file for Python 3.8 (cp38 index in the .whl filename). You need to download python_igraph‑0.7.1.post6‑cp37‑cp37m‑win_amd64.whl instead. 

Please, use it and retry the installation.

**Comment by maldeer-Winlab** [comment]
@nikfrlv 

I see, my bad. I will install the one for python 3.7.
Should I repeat 1 & 2, given I closed the Anaconda terminal and now will open a new terminal?
Thank you

**Comment by nikfrlv** [comment]
@maldeer-Winlab 

if you activate the same environment all the installed packages will be available, so I think that (1) and (2) are unnecessary.

**Comment by maldeer-Winlab** [comment]
@nikfrlv 

I did these steps but still getting an error!

If no hope, please be informed that I appreciate your help. 
Thank you
![image](https://user-images.githubusercontent.com/59928475/80735312-82336300-8ade-11ea-89b7-a9ad117e0391.png)

**Comment by nikfrlv** [comment]
@maldeer-Winlab 

then, I believe, you have windows 10 x32 -- python_igraph‑0.7.1.post6‑cp37‑cp37m‑win32.whl should work. Unfortunately, in this case, my .whl file for pyunicorn will not work with your platform either.

**Comment by maldeer-Winlab** [comment]
@nikfrlv 
it is 64 bit

![image](https://user-images.githubusercontent.com/59928475/80736281-ea367900-8adf-11ea-8eef-055d81534269.png)

**Comment by bscully27** [comment]
Any chance you could make a wheel file for python3.6, windows64?

**Comment by nikfrlv** [comment]
Hi @bscully27,
the problem is that pyunicorn is originally written in Python 3.7 (see documentation).

**Comment by neelesh2k** [comment]
> Hi Jonathan @jdonges,
> 
> I've uploaded the .whl file in this repository: https://github.com/nikfrlv/pyunicorn-windows-whl.
> I encourage Windows-users to download it and use it in their research.
> 
> Best,
> Nikita

I downloaded the wheel file and it worked. Thank you.

**Comment by Mattyboi123** [comment]
the wheel file works  to install pyunicorn. However, there are still errors that preclude its utilisation.
importing the pyunicorn module into spyder IDE failed with 

  ```
File "C:\users\fbsmawadmin\Anaconda3_\lib\site-packages\pyunicorn\__init__.py", line 43, in <module>
    from setup import __version__

ModuleNotFoundError: No module named 'setup'
```

I thought perhaps the line was erroneous but `commenting` out the line in the init.py script and trying again gave a new error
```

pyunicorn: Package netCDF4 could not be loaded. Some functionality in class Data might not be available!
pyunicorn: Package netCDF4 could not be loaded. Some functionality in class NetCDFDictionary might not be available!
```

has anybody got any stories of having been able to successfully use pyunicorn in spyder using python 3.7 on windows 10??

Cheers

Matt

**Comment by rockmosi** [comment]
@nikfrlv thank you 
your solution is working very well.
os: win10 64bit
python: 3.7

if any one need to check virtual env, check my env
![pyunicorn](https://user-images.githubusercontent.com/45458569/86508544-d24ede80-be1b-11ea-8a03-7c05437428c9.jpg)

**Comment by Abinesh1996** [comment]
> @XMAHA @Nikos-T @yop0 hi, guys! After a few hours of coding I've compiled the .whl file for pyunicorn package. It works correct - tested for Windows 10 x64. Please, contact the developers of pyunicorn as I have sent the .whl file them.

Hello, 
Have u developed whl file for python 3.8?! Is any other way I can install pyunicorn on python 3.8?

**Comment by Abinesh1996** [comment]
> the wheel file works to install pyunicorn. However, there are still errors that preclude its utilisation.
> importing the pyunicorn module into spyder IDE failed with
> 
> ```
> File "C:\users\fbsmawadmin\Anaconda3_\lib\site-packages\pyunicorn\__init__.py", line 43, in <module>
>   from setup import __version__
> 
> ModuleNotFoundError: No module named 'setup'
> ```
> 
> I thought perhaps the line was erroneous but `commenting` out the line in the init.py script and trying again gave a new error
> 
> ```
> 
> pyunicorn: Package netCDF4 could not be loaded. Some functionality in class Data might not be available!
> pyunicorn: Package netCDF4 could not be loaded. Some functionality in class NetCDFDictionary might not be available!
> ```
> 
> has anybody got any stories of having been able to successfully use pyunicorn in spyder using python 3.7 on windows 10??
> 
> Cheers
> 
> Matt

@Mattyboi123 got any solution?! I'm stuck with the same issue

**Comment by Lu-Geo** [comment]
> Hi Jonathan @jdonges,
> 
> I've uploaded the .whl file in this repository: https://github.com/nikfrlv/pyunicorn-windows-whl.
> I encourage Windows-users to download it and use it in their research.
> 
> Best,
> Nikita

Much appreciated!!!It has been bothering me for several days!

**Comment by abhijithsbabu** [comment]
> > the wheel file works to install pyunicorn. However, there are still errors that preclude its utilisation.
> > importing the pyunicorn module into spyder IDE failed with
> > ```
> > File "C:\users\fbsmawadmin\Anaconda3_\lib\site-packages\pyunicorn\__init__.py", line 43, in <module>
> >   from setup import __version__
> > 
> > ModuleNotFoundError: No module named 'setup'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I thought perhaps the line was erroneous but `commenting` out the line in the init.py script and trying again gave a new error
> > ```
> > 
> > pyunicorn: Package netCDF4 could not be loaded. Some functionality in class Data might not be available!
> > pyunicorn: Package netCDF4 could not be loaded. Some functionality in class NetCDFDictionary might not be available!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > has anybody got any stories of having been able to successfully use pyunicorn in spyder using python 3.7 on windows 10??
> > Cheers
> > Matt
> 
> @Mattyboi123 got any solution?! I'm stuck with the same issue

Any solution found yet?

**Comment by nikfrlv** [comment]
@abhijithsbabu unfortunately, this .whl does not provide full access to functionality of the pyunicorn package, because some dependencies are still missing. However, some modules like RecurrencePlots (which I mostly use) are working well.
If anyone has a better solution, please, share it here.

**Comment by ntfrgl** [comment]
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.
